import type { Metadata } from "next";
import "./globals.css";
import { satoshi } from "@/fonts";

export const metadata: Metadata = {
  title: "Cliply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.className} font-medium antialiased`}>
        {children}
      </body>
    </html>
  );
}
